### ISSUE TITLE
Resizing the image within the container

### ISSUE THREAD

**Issue by AnirudhPanda** [Opentek-Org/opentek#116]
### Description

Fix the issue below:
- Check the other events page and see where the image is
- Resize accordingly

### Screenshots

<img width="955" alt="Screenshot 2021-11-01 at 4 30 32 PM" src="https://user-images.githubusercontent.com/66218496/139661890-f4103dd3-80b6-4e41-b20b-c37a602cd347.png">

### Do you want to work on this issue?

- [ ] I want to work on this issue.

**Comment by ishikajn8126** [comment]
I would like to work on this issue.

**Comment by prachigarg19** [comment]
I'd like to fix this problem . Please assign it to me

**Comment by AnirudhPanda** [comment]
> I would like to work on this issue.

Assigned for 2 days!

Happy Coding!
