### ISSUE TITLE
Slow transition via navbar

### ISSUE THREAD

**Issue by ishikajn8126** [Opentek-Org/opentek#118]
### Description

The transition from one section to another via navbar is quite slow, which accounts to bad user experience.
Relevant changes should be made to reduce this time.

### Screenshots

https://user-images.githubusercontent.com/72145053/144556160-f6f80ecf-bba9-4803-814d-25bcf1d815c5.mp4

### Additional information

N/A

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by AnirudhPanda** [comment]
Assigning this to you!

**Comment by Jashwanth-k** [comment]
I had fixed the Slow transition, should i open a pull request 

https://user-images.githubusercontent.com/89581005/144702531-b2960e3e-adf0-4dd8-ac35-41c50a1ae70a.mp4

**Comment by nileshkr17** [comment]
@Jashwanth-k Great work! 🎉 .
Open a pull request.

**Comment by Jashwanth-k** [comment]
@AnirudhPanda please assign it to me under SWOC, i had fixed the issue

**Comment by nileshkr17** [comment]
Hey @Jashwanth-k ,
Assigning this to you!
