### ISSUE TITLE
Show Login/Signup form when user clicks on Events/Programs

### ISSUE THREAD

**Issue by ishikajn8126** [Opentek-Org/opentek#119]
**Is your feature request related to a problem? Please describe.**
Right now, if the user clicks on Tune In/Participate, nothing happens if the user is not logged in because the cursor-event is set to none.
![image](https://user-images.githubusercontent.com/72145053/144556835-cb7910e9-3ff3-4d4c-b47e-9254a910152d.png)

**Describe the solution you'd like**
Instead of setting cursor-event: none, login/signup form can be displayed when the user clicks on Tune In/Participate.

**Describe alternatives you've considered**
N/A

**Comment by ArmaLukas** [comment]
<a href="https://opensea.io/" title="Buy on OpenSea" target="_blank"><img style="width:220px; border-radius:5px; box-shadow: 0px 1px 6px rgba(0, 0, 0, 0.25);" src="https://storage.googleapis.com/opensea-static/Logomark/Badge%20-%20Available%20On%20-%20BW.png" alt="Available on OpenSea" /></a>

**Comment by ArmaLukas** [comment]
ለተወሰነ ጊዜ አጥፊ ሕይወት ለሰው ልጅ አስደሳች ግን አድካሚ ሁኔታን ያስከትላል። ሁሉም ነገር አሰልቺ ከሆነ ወይም ብዙ መጥፎ ነገሮች ሲከሰቱ አበረታች ንጥረ ነገሮችን እንጠቀማለን ወዘተ.

**Comment by AnirudhPanda** [comment]
Would you like to take it?

**Comment by pritmanvar** [comment]
I would like to work on this

**Comment by Karan-Dhingra** [comment]
I have added this feature please review it

**Comment by Karan-Dhingra** [comment]
#129
