### ISSUE TITLE
Contributing.md file not linked in README

### ISSUE THREAD

**Issue by ishikajn8126** [Opentek-Org/opentek#120]
### Description

Clicking on CONTRIBUTE.md in README is throwing 404 error page.

### Screenshots

![image](https://user-images.githubusercontent.com/72145053/144557587-e08937ba-35c5-4133-9149-785c0e76a0db.png)

### Additional information

N/A

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by iArchitSharma** [comment]
Can I work on this issue?

**Comment by nileshkr17** [comment]
#124
