### ISSUE TITLE
Implement AOS (Animate on Scroll) in website

### ISSUE THREAD

**Issue by Atif0604** [Opentek-Org/opentek#121]
**Describe the solution you'd like**
I would like to add AOS Library for smooth loading of different section of home page

Please Assign me this issue under SWOC'21

**Comment by AnirudhPanda** [comment]
What is your idea regarding it?
A short desc of what you are planning to do would help!

**Comment by Atif0604** [comment]
Like in the features section the left cards will be coming from left and right cards will be coming from right 
similarly in the about the image will be coming from left and and the paragraph will be coming from right 
like that in the whole webpage
@AnirudhPanda
