### ISSUE TITLE
Adjusting redirect from projects page 

### ISSUE THREAD

**Issue by Yash-RajSingh** [Opentek-Org/opentek#122]
### Description

After clicking on the home button on the projects, the new page opens up in a new tab rather than the same tab. I would like to fix this so that the page redirects the current tab to the destination.
I would like to work on this as a contributer in SWOC 21
### Screenshots

https://user-images.githubusercontent.com/85413348/144930014-58aac4c8-4563-4bf1-b3cd-509e9f518429.mp4

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by Bikramjit21** [comment]
I can also work on this!
