### ISSUE TITLE
Adjusting redirects from projects page-2

### ISSUE THREAD

**Issue by Yash-RajSingh** [Opentek-Org/opentek#123]
### Description

After clicking on the projects button in the footer of the projects page, the page shows an error instead of loading the same page again. I would like to work on this as a contributer in SWOC 21

### Screenshots

https://user-images.githubusercontent.com/85413348/144930286-53e8274e-a718-44f3-b674-72aef57aca8e.mp4

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by AnirudhPanda** [comment]
Is the behavior due to Login issue??

**Comment by Yash-RajSingh** [comment]
I think it's because of target location which is being passed in the anchor tag which I believe is unnecessary.

**Comment by Yash-RajSingh** [comment]
> > I think it's because of target location which is being passed in the anchor tag which I believe is unnecessary.
> 
> Okay assigning the issue to you!

And what about the similar issue that I raised? Am I going to be assigned that one too?

**Comment by Yash-RajSingh** [comment]
I have fixed this issue and raised a PR #140 . Kindly please review it and merge @AnirudhPanda . Also can you please add SWOC tag in the issue.
