### ISSUE TITLE
Texture line on the header should be removed

### ISSUE THREAD

**Issue by Swati002** [Opentek-Org/opentek#125]
### Description

Texture line on the header should be removed

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by Swati002** [comment]
Assign this issue to me @AnirudhPanda

**Comment by sshiv5768** [comment]
Hey, @AnirudhPanda Can i work on this issue?

**Comment by nileshkr17** [comment]
> Hey, @AnirudhPanda Can i work on this issue?
 
Ya!
Assigning this to you!
