### ISSUE TITLE
Quick links at footer of site does not work the same as home page in other pages

### ISSUE THREAD

**Issue by iArchitSharma** [Opentek-Org/opentek#136]
### Description

**DESCRIPTION**
Home page- https://opentek.live/
Tutorial page - https://opentek.live/pages/tutorial.html

1)First try opening the home page and tutorial page and navigate to the footer section
2)than try opening and hovering on the links you will see the difference

_I would like to work on this issue_
**FIX** 
The footer section of site in other pages is not updated

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by SatYu26** [comment]
Hey, @iArchitSharma I would like to take on this issue.
