### ISSUE TITLE
The image of one of the maintainer is not visible in About Us page.

### ISSUE THREAD

**Issue by SatYu26** [Opentek-Org/opentek#139]
### Description

As you can see in the below Screenshot, the image of the maintainer on the About Us page is not visible, I realized that the URL from which it is fetching image does not exist.

### Screenshots

![Screenshot 2022-01-02 060314](https://user-images.githubusercontent.com/41650056/147863133-53611360-f610-4166-8b3c-1b48141cc6a3.png)

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by iArchitSharma** [comment]
Hey, I think image has been deleted
I can fix this issue if someone can provide me the profile image of Sunil

**Comment by iArchitSharma** [comment]
Made a PR #141
