### ISSUE TITLE
Projects are not loading when domain is selected as web development 

### ISSUE THREAD

**Issue by ankush0024** [Opentek-Org/opentek#152]
### Description

Hi when I select a project and comes back to opentek website the projects are not loaded . 

### Screenshots
<img width="1440" alt="Screenshot 2022-12-19 at 10 04 46 PM" src="https://user-images.githubusercontent.com/71636137/208474970-e70e5e51-587e-4aa4-bc2c-f06c344150ff.png">

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by AnirudhPanda** [comment]
It seems fine to me.
Please check once

**Comment by bhavyanarnoli** [comment]
I want to work on this issue.

**Comment by satmm** [comment]
I want to work on this issue

**Comment by sunny0625** [comment]
No Issue found!
