### ISSUE TITLE
Update README.md [GSSoC'23]

### ISSUE THREAD

**Issue by DrVickie8** [Opentek-Org/opentek#154]
There is a typo in the 'Try out OpenTek' link, this link opens a blank page.

**Comment by DrVickie8** [comment]
I want to be assigned to this issue.
I will update the link in the README.md file

**Comment by shraddha761** [comment]
Hye request to assign this issue to me under GSSOC'23

**Comment by sunny0625** [comment]
Can you elaborate more about the issue?

**Comment by DrVickie8** [comment]
Sure @sunny0625 
In the README.md file, in the paragraph, before the 'Read our blog post' hyperlink text, there is a 'Try out Opentek' that is supposed to link to the webpage, but instead it links to an error page.
I want to fix this error.

**Comment by sunny0625** [comment]
Okay Assigning you @DrVickie8 this issue!

**Comment by DrVickie8** [comment]
Thank you! @sunny0625

**Comment by DrVickie8** [comment]
I just created a PR #283

**Comment by sunny0625** [comment]
PR Merged
