### ISSUE TITLE
Improving UI

### ISSUE THREAD

**Issue by sumitkr2000** [Opentek-Org/opentek#156]
**Is your feature request related to a problem? Please describe.**
Hey @AnirudhPanda I want to improve the UI of your website. Please assign me this issue. Thank you!

**Describe the solution you'd like**
improving the home page and social button

**Describe alternatives you've considered**

**Additional context**

**Comment by Uzmakh** [comment]
I am interested in this issue#156

**Comment by sumitkr2000** [comment]
@AnirudhPanda Please assign me this issue.

**Comment by AnirudhPanda** [comment]
> @AnirudhPanda Please assign me this issue.

hey can you please elaborate on how are you planning on doing this?
@sumitkr2000

**Comment by tripathishipra** [comment]
Hi , I am contributor under GSSOC'23 and I am eager to showcase my skills and make a meaningful contribution to this project.
Kindly assign me this issue@AnirudhPanda

**Comment by sumitkr2000** [comment]
@AnirudhPanda I want to add a hover effect on the social button so that when the users hover on it the color changes to the respective official color of social media.

**Comment by sumitkr2000** [comment]
@AnirudhPanda Please assign me this issue so that I can start working on it.
