### ISSUE TITLE
FEATURE : Fixed Navbar And some changes in paddings

### ISSUE THREAD

**Issue by MOHDNEHALKHAN** [Opentek-Org/opentek#161]
@AnirudhPanda , please assign me this issue as a gssoc'2023 contributor  I want to work on this issue
This feature will stick the navbar on top of the webpage and looks good
Screenshot attached for changes

![Screenshot 2023-05-20 231618](https://github.com/Opentek-Org/opentek/assets/125626654/f84fb7db-9a62-4968-9d12-53c53b8a814f)

**Comment by dosasambhar** [comment]
may you please assign me this work under Gssoc'23 label?

**Comment by sunny0625** [comment]
Are you still want to work on this issue?
