### ISSUE TITLE
Adding hover effect in the video cards under the 'tutorials section'

### ISSUE THREAD

**Issue by Ashna56** [Opentek-Org/opentek#163]
Under the tutorials section, the video cards do not have a hover effect.
In order to have a more engaging user experience, we should add the hover effect on the video card present under this section.

I would like to work on this feature under GSSOC'23

**Comment by sunny0625** [comment]
Are you still up for this?

**Comment by Ashna56** [comment]
yes i am

**Comment by sunny0625** [comment]
Assigned

**Comment by sunny0625** [comment]
Are you still working on this issue?
