### ISSUE TITLE
Navbar also scrolls up with whole screen

### ISSUE THREAD

**Issue by Akanksha-202** [Opentek-Org/opentek#165]
### Description

Navbar needs to be static so that it is easy for the user to navigate through all the options without scrolling all the way up to find that option.

### Screenshots

![image](https://github.com/Opentek-Org/opentek/assets/100708686/54f0ec61-4f3e-4698-a880-2c23b9b78e59)
No Navbar

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by sunny0625** [comment]
Looks like the issue is solved!
