### ISSUE TITLE
Styling of project section is not fixed 

### ISSUE THREAD

**Issue by Mihir2423** [Opentek-Org/opentek#170]
### Description

The styling of the project section is not proper. There is a large margin between the search input and the boxes. Also the box styling is not fixed.

Can i work on this issue under GSSOC '23

### Screenshots

<img width="934" alt="Screenshot 2023-05-21 at 2 52 56 PM" src="https://github.com/Opentek-Org/opentek/assets/93427284/7be3743a-79cc-431c-86f0-cccfcdc49049">

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by sunny0625** [comment]
Issue solved already!
