### ISSUE TITLE
FEATURE( adding some animation/transitions in cards of project section  )

### ISSUE THREAD

**Issue by Heismanish** [Opentek-Org/opentek#178]
**Is your feature request related to a problem? Please describe.**
A website without interactive animations always looks kinda dull, so here I would like to make some changes in the the ui of the cards in projects section by adding some animations.

**Describe the solution you'd like**
I want to to add some transitions to the cards in the project sections and make a little more vibrant.

**Additional context**
![Screenshot from 2023-05-21 16-08-02](https://github.com/Opentek-Org/opentek/assets/92051445/bcd50e93-f516-4d94-9bc1-826a7779b58b)

**Comment by sunny0625** [comment]
@AnirudhPanda is gtg?
