### ISSUE TITLE
FEATURE: Enhance Back To Top Button

### ISSUE THREAD

**Issue by ChinatuL** [Opentek-Org/opentek#181]
I have noticed that the Back To Top button is barely visible at the footer except for the arrow pointing upwards. 

![Screenshot (132)](https://github.com/Opentek-Org/opentek/assets/97689140/fcd44824-062e-462d-97b8-8e6cb1af69ab)

I would like to add an animation and transition to the button to make it more visible.

Kindly assign this issue to me under Gssoc'23.

**Comment by sunny0625** [comment]
Sorry for the delay in the response.

do you want to take this issue?

**Comment by ChinatuL** [comment]
@sunny0625 Thank you for assigning me. Kindly add the gssoc23 label so my contribution can count.
