### ISSUE TITLE
FEATURE - To open the Resources in new tab, instead of existing tab

### ISSUE THREAD

**Issue by KashiwalHarsh** [Opentek-Org/opentek#183]
In the resource route, when I clicked on the resource URL, it doesn't open in the new tab.

I want to add the feature so that when clicked on the resource URL, it takes the user to a new tab for a better experience and to not distract/take away user from the website

**Comment by harmeetsingh11** [comment]
I would like to work on this issue. Can you please assign me under GSSOC'23?

**Comment by steffigeorge** [comment]
If the issue hasn't been resolved, can you please assign it to me?

**Comment by sunny0625** [comment]
@AnirudhPanda is this issue solved?

**Comment by AnirudhPanda** [comment]
not needed
