### ISSUE TITLE
UI Improvement in the blog section

### ISSUE THREAD

**Issue by shruti8302** [Opentek-Org/opentek#188]
As a part of GSSOC'23, I would like to make changes in the UI of the blog section by adding transition on the cards as well as make changes in the font to increase the readability of the blogs, etc.
 Kindly assign me this issue.

**Comment by sunny0625** [comment]
Assigned

**Comment by shruti8302** [comment]
> Assigned

Thank you for assigning this issue to me. Please give me time till 9 july, I will surely complete the task.

**Comment by sunny0625** [comment]
How was it going?

**Comment by shruti8302** [comment]
I am sorry due to some personal issue I won't be able to complete the task. I am unassigning myself from this issue.
