### ISSUE TITLE
Clicking on logo redirects us to a new tab

### ISSUE THREAD

**Issue by An525ish** [Opentek-Org/opentek#189]
### Description

Clicking on logo redirects us to a new tab instead it should just navigate to the home page 

### Screenshots

https://github.com/Opentek-Org/opentek/assets/93612051/55866a5a-2ddb-431e-9783-043f5034c843

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by ashankritwik07** [comment]
@ An525ish please assign me this problem under Gssoc'23. #189

**Comment by sunny0625** [comment]
Seem like the Issue is solved.
