### ISSUE TITLE
FEATURE :- Update cards of features section. 

### ISSUE THREAD

**Issue by Pragati-3003** [Opentek-Org/opentek#195]
I would like to update the cards of the features section by improving the existing ui to make this section more attractive. 
![IMG_20230522_220610](https://github.com/Opentek-Org/opentek/assets/132778037/b1b7def3-85be-41f4-b174-6fc04417fafb)
So, please assign this issue to me under GSSOC'23. 
Thanking you.

**Comment by sunny0625** [comment]
Can you elaborate on your purpose?

**Comment by Pragati-3003** [comment]
> Can you elaborate on your purpose?

I would like to add the hover effects and box-shadows to the cards. 
Also would like to adjust the css.

**Comment by sunny0625** [comment]
is this feature needed?
cc: @AnirudhPanda
