### ISSUE TITLE
Footer Revamp

### ISSUE THREAD

**Issue by AnirudhPanda** [Opentek-Org/opentek#21]
We want the footer links to be centered and some different animation than just moving right after hovering to it

**Comment by neeraj15022001** [comment]
Footer right now seems messy we need to reduce font a bit and make elements breathe and instead of side animation underline with color change can be a catchy option

**Comment by AnirudhPanda** [comment]
> Footer right now seems messy we need to reduce font a bit and make elements breathe and instead of side animation underline with color change can be a catchy option

Yeah footer needs some good styling

**Comment by neeraj15022001** [comment]
assign this too if no one else is picking

**Comment by neeraj15022001** [comment]
in progress with seperate PR
