### ISSUE TITLE
FEATURE: Create a sticky Navbar

### ISSUE THREAD

**Issue by ishita80** [Opentek-Org/opentek#223]
**Is your feature request related to a problem? Please describe.**
The Navbar on the website is not sticky and so the user can't go to any other nav link at any point of the page except the top.

**Describe the solution you'd like**
I will make the Navbar sticky, so that it is available to the user all the time.

**Comment by ishita80** [comment]
@AnirudhPanda Please assign this issue to me.

**Comment by sunny0625** [comment]
Look Like issue is solved
