### ISSUE TITLE
[Mobile] Navbar Styling 

### ISSUE THREAD

**Issue by AnirudhPanda** [Opentek-Org/opentek#23]
![i1](https://user-images.githubusercontent.com/66218496/131460575-ad1884ab-d26d-43f3-a033-86b5b4550e2e.PNG)

On clicking the hamburger icon the X icon should appear, also a little border-radius around the dropdown would look neat.

**Comment by neeraj15022001** [comment]
I would like to work

**Comment by neeraj15022001** [comment]
@AnirudhPanda add me as assignee as it is easy for me to sort issues by assignee

**Comment by nileshkr17** [comment]
@AnirudhPanda hello sir
i would like to do it.

**Comment by neeraj15022001** [comment]
in progress with seperate PR

**Comment by AnirudhPanda** [comment]
> in progress with seperate PR

I guess its done

**Comment by neeraj15022001** [comment]
@AnirudhPanda not reflecting on main website just check once and ping me status about this issue
