### ISSUE TITLE
[GSSOC'23] Show projects without selecting domain

### ISSUE THREAD

**Issue by pavitrachavda97** [Opentek-Org/opentek#237]
**Problem**
If someone want to contribute to more than one domain than they have to change domain it is not comfortable.

**Solution**
Show all domain's project and if anyone wants to show project according to domain than they can also choose domain.

**Comment by AnirudhPanda** [comment]
elaborate

**Comment by pavitrachavda97** [comment]
In the project showing section, we are not able to see all projects from all domains, so I want to add the feature of showing all projects at first, and if someone wants to see projects from a particular domain, they can choose their domain and see projects from that domain.

**Comment by AnirudhPanda** [comment]
go for it
