### ISSUE TITLE
Adding a testimonial section

### ISSUE THREAD

**Issue by Anamika-Ratna** [Opentek-Org/opentek#239]
Hello , I would like to add a review section where some of the top reviews would be displayed .
So for this review section I would ask a favor from you . Kindly circulate the google form so that I can recieve the reviews . Some of the top reviews will be displayed on the website .
Google form: https://forms.gle/F4Q8VmsrxM5REny58

Therefore I request you to kindly assign me this task under the tag GSSoC- 23

**Comment by AnirudhPanda** [comment]
Sorry for the delay in the response.

do you want to take this issue?

**Comment by Anamika-Ratna** [comment]
@AnirudhPanda 
Yeah sure !! I would like to work on this issue.
Do assign me this issue please .

**Comment by Anamika-Ratna** [comment]
Hello @AnirudhPanda, may you please assign me this issue . I would complete the work within a couple of days .

**Comment by AnirudhPanda** [comment]
> Hello @AnirudhPanda, may you please assign me this issue . I would complete the work within a couple of days .

Done

**Comment by Anamika-Ratna** [comment]
Hello @AnirudhPanda I have added the testimonial section . Kindly have a look at it .
