### ISSUE TITLE
Add a logo to the navigation bar

### ISSUE THREAD

**Issue by HarshJain100** [Opentek-Org/opentek#241]
I can Add a logo to the navigation bar, Please assign this to me.

**Comment by kalashjain23** [comment]
> Hi @kalashjain23 , I can Add a logo to the navigation bar, Please assign this to me.

Hey @HarshJain100, I think you have pinged me by mistake. I'm not a maintainer for this repository xD.

**Comment by HarshJain100** [comment]
> > Hi @kalashjain23 , I can Add a logo to the navigation bar, Please assign this to me.
> 
> Hey @HarshJain100, I think you have pinged me by mistake. I'm not a maintainer for this repository xD.

Lmao, Sorry for the misunderstanding.
