### ISSUE TITLE
Divs of project section's web dev portion is of not proper height

### ISSUE THREAD

**Issue by DhairyaMajmudar** [Opentek-Org/opentek#255]
### Description

To remove the bug of the web dev section os project page by applying proper height to them

### Screenshots

![Screenshot 2023-06-08 at 18-37-40 Opentek Programs](https://github.com/Opentek-Org/opentek/assets/124715224/222411ca-5115-4a96-820b-f995498981a9)

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by DhairyaMajmudar** [comment]
Please assign this issue to me under GSSoC'23. I will solve this issue with the help of CSS and HTML

**Comment by AnirudhPanda** [comment]
assigned it to you

**Comment by DhairyaMajmudar** [comment]
Thank You @AnirudhPanda for assigning me this issue

**Comment by AnirudhPanda** [comment]
I guess this issue is solved??
cc: @sunny0625

**Comment by sunny0625** [comment]
> I guess this issue is solved?? cc: @sunny0625
Not yet!
![image](https://github.com/Opentek-Org/opentek/assets/76521579/c5d82188-8f14-466c-a876-347f9b93915a)
