### ISSUE TITLE
Feature: Want to Add Dark and Light mode toggle and want to add Color Themes in the website

### ISSUE THREAD

**Issue by lakhan06** [Opentek-Org/opentek#258]
**Is your feature request related to a problem? Please describe.**
My feature is  regarding to improve the user Experience of website.

**Describe the solution you'd like**
To Improve the  User experience I want to add color themes in the website so that the user have 4-5 color themes and he can choose color themes according to his/her choice. 

I also want to add a dark-light mode toggle button so that user can switch to dark or light mode according to its convenience

**Comment by AnirudhPanda** [comment]
assigned

**Comment by Kajal2468** [comment]
I want to add Dark & Light mode in the website with some more funcitonality , Please assign it to me

Thank You!

**Comment by AnirudhPanda** [comment]
This isn’t required 
Thanks
