### ISSUE TITLE
Two scroll bars in Project section 

### ISSUE THREAD

**Issue by SoundaryaKoutharapu** [Opentek-Org/opentek#282]
#### Steps to reproduce:

1. go to "website"
2. click on projects in navbar
3.  go down
4. click on scroll to top

When we click on scroll to top, it's not taking us to top.
 I'd like to fix this. 
 Could you please assign this issue to me under Gssoc'23.

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by sunny0625** [comment]
I think it's Coz of the 2 scroll bars. Are you willing to solve it??

**Comment by SoundaryaKoutharapu** [comment]
@sunny0625 Yes I would like to fix this.

**Comment by sunny0625** [comment]
Okay change the title then I will assign this issue!

**Comment by SoundaryaKoutharapu** [comment]
@sunny0625 changed

**Comment by SoundaryaKoutharapu** [comment]
@sunny0625  
#### It is because missing of  "id=banner" in <section>
#### After fixing that,  the look of project page has changed.
#### Because it was applied default styling, which was applied to all pages. (like about, tutorial).
#### So, Can I make the pull request for removing the scroll bar and fixing the working of scroll to top .
#### Or should I have to fix the styling part.? (as it was default to all pages)


![2023-06-11](https://github.com/Opentek-Org/opentek/assets/71914071/aaf865a1-ec08-4dc5-8a1f-a9bb76c02bac)
![2023-06-11 (1)](https://github.com/Opentek-Org/opentek/assets/71914071/436679ab-b50c-4ec9-9093-a7ac52b44453)

**Comment by AnirudhPanda** [comment]
this is already fixed ig @sunny0625

**Comment by SoundaryaKoutharapu** [comment]
@AnirudhPanda  but still scroll to top is not working.
and I fixed that issue.
Shall I make pull request for that.
