### ISSUE TITLE
Back-to-top button not working on Projects page

### ISSUE THREAD

**Issue by ChinatuL** [Opentek-Org/opentek#285]
### Description

On the projects page of the website, the back-to-top button does not scroll the page up to the beginning.

[bug-backtotop-btn.webm](https://github.com/Opentek-Org/opentek/assets/97689140/6624ac42-c421-4aeb-b611-1ad241d5b117)

I would like to fix this as a gssoc23 contributor.

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by sunny0625** [comment]
This issue is already assigned

check for reference #282

**Comment by sunny0625** [comment]
Issue already Solved
