### ISSUE TITLE
Style - Improve Card

### ISSUE THREAD

**Issue by Ayush9951** [Opentek-Org/opentek#291]
Hi, I am a contributor in GSSOC'23.
I want to work on Improving the alignment of card elements.
please assign me this task undel label gssoc'23

![Screenshot 2023-06-12 191235](https://github.com/Opentek-Org/opentek/assets/60573378/e36dd112-1337-4f00-9d8c-42ebc4a07e64)

**Comment by AnirudhPanda** [comment]
it was meant to be like that
