### ISSUE TITLE
Project Card UI Improvement

### ISSUE THREAD

**Issue by SubhamB2003** [Opentek-Org/opentek#292]
Hey, These project section cards are not looking good that much. I want to improve it.

Previous
![image](https://github.com/Opentek-Org/opentek/assets/94003231/ae5fe62f-af3a-409c-94ef-940943dedd1a)

After improvement
![image](https://github.com/Opentek-Org/opentek/assets/94003231/df900b2e-8370-43ab-aca6-b36740a49821)

Can you please assign it to me under GSSOC'23

**Comment by AnirudhPanda** [comment]
looks the same to me

**Comment by SubhamB2003** [comment]
> looks the same to me

Actually, here I am adding some padding, changing text font, changing the text size, adding some space, and on hover zoom in effect.

**Comment by prash240303** [comment]
can I get the following issue assigned?  

the design proposed : 
![Frame 39](https://github.com/Opentek-Org/opentek/assets/93905743/9e33ca7e-8eb2-47e6-9f26-8a682b18ba7f)

**Comment by prash240303** [comment]
can you assign the following issue to me? 
the proposed design : 
![Frame 39](https://github.com/Opentek-Org/opentek/assets/93905743/5c701dcd-2b9c-446d-87dd-13cac74bdb74)

**Comment by AnirudhPanda** [comment]
> can you assign the following issue to me? the proposed design : ![Frame 39](https://user-images.githubusercontent.com/93905743/245254839-5c701dcd-2b9c-446d-87dd-13cac74bdb74.png)

done

**Comment by sunny0625** [comment]
PR Merged
