### ISSUE TITLE
[Bug]: Scrolling Behavior is Not Move From Bottom to Top Smoothly

### ISSUE THREAD

**Issue by NarendraKoya999** [Opentek-Org/opentek#293]
### When I am Clicking on Below Scroll Bar Icon:
<img width="953" alt="opentech-1" src="https://github.com/Opentek-Org/opentek/assets/84512164/2860ae01-e4af-4df3-842b-25f9acf0755e">

### Actual Behavior: ( When Click on Scroll Bar Icon, It stops at the Respective Below Image)
<img width="953" alt="opentek-2" src="https://github.com/Opentek-Org/opentek/assets/84512164/f1e2cc5a-7663-415e-8598-6a2f630193b5">

### Expected Behavior: (Expect Scroll Bar Fully Stops At the` Join us on Discord` Header Bar)
<img width="960" alt="opentek-3" src="https://github.com/Opentek-Org/opentek/assets/84512164/f2c69282-31a5-4b3f-a08c-8aa6a9782072">

## Note:

- One way of Better To Solve This Issue is, I have already Raised One Issue . It's Close to This Present Issue.
- Another Way , By Reference That Issue No < #242 > and Solve More Conveniently.

### Do you want to work on this issue?

- [ ] I want to work on this issue.

**Comment by AnirudhPanda** [comment]
assigned @NarendraKoya999

**Comment by sunny0625** [comment]
Are you still up?
