### ISSUE TITLE
Link not available for joining discord on the top of the page 

### ISSUE THREAD

**Issue by dwivedishrey** [Opentek-Org/opentek#301]
### Description

I want to add a link so that user can join by clicking on the discord icon on the top of the page only.
![Screenshot (543)](https://github.com/Opentek-Org/opentek/assets/97790062/43dcb29a-a29e-4543-88b5-b76b6566669a)

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by sunny0625** [comment]
Start your contributing journey @dwivedishrey!

**Comment by sunny0625** [comment]
Merged
