### ISSUE TITLE
 Inability to Close Settings Menu When Clicking on Settings Icon in Projects Page

### ISSUE THREAD

**Issue by rishiofficial** [Opentek-Org/opentek#305]
### Description

In the Projects page of our application, there is a settings menu that appears when the user clicks on the settings icon. However, we have encountered an issue where clicking on the settings icon does not close the settings menu as expected. This issue disrupts the user experience and prevents users from effectively managing project settings.

### Screenshots

https://github.com/Opentek-Org/opentek/assets/109091515/cc132597-6d89-4887-8f39-f64ae8316a22

### Additional information

Steps to Reproduce:

Navigate to the Projects page.
Locate a project with the settings icon.
Click on the settings icon to open the settings menu.

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by mandliyarajendra11** [comment]
i want   to work on this issue @AnirudhPanda 
Can I open a new issue or can you reopen this one?
