### ISSUE TITLE
Resolve Join us on Discord issue

### ISSUE THREAD

**Issue by MisterMickey** [Opentek-Org/opentek#308]
### Description

When I tried to click on the Join us on Discord anchor tag on the top of the Opentek website then it's not redirecting to the discord channel, It's not behaving like a hyperlink, I want to fix this issue. 

### Screenshots

![Screenshot from 2023-06-16 10-15-17](https://github.com/Opentek-Org/opentek/assets/93720428/8ed4dae2-c940-47b6-917c-2edbdaca9d44)

### Additional information

Also, the mouse cursor is not changing to a pointer, I'll fix that too.

Kindly assign me this issue under gssoc23

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by sunny0625** [comment]
@AnirudhPanda is this issue already assigned?

**Comment by sunny0625** [comment]
Closing this issue for reference #301
