### ISSUE TITLE
FEATURE: Login Form "Sign up" Line Alignment

### ISSUE THREAD

**Issue by iamRabia-N** [Opentek-Org/opentek#315]
**Is your feature request related to a problem? Please describe.**
No. It's an enhancement in the existing design.

**Describe the solution you'd like**
Alignment of the line "Don't have an account? Sign up" from left-aligned to center-aligned.

**Describe alternatives you've considered**
Correct Alignment

**Additional context**
_Current Alignment_
![opentek (2)](https://github.com/Opentek-Org/opentek/assets/115794049/5a243416-9f7a-44e0-a93b-01188dc71f7e)

_Expected Output Alignment_
![opentek (1)](https://github.com/Opentek-Org/opentek/assets/115794049/2d7a64a0-31c2-42c8-b18c-041e475f4e53)

**Comment by AnirudhPanda** [comment]
this was provided by auth0

**Comment by iamRabia-N** [comment]
So, no need to improve it?
