### ISSUE TITLE
theme colors option close when we click on anywhere on page or after selecting theme

### ISSUE THREAD

**Issue by weberankit** [Opentek-Org/opentek#334]
web behaviour::   after choose theme color it close when we click on setting icon 
Improvement--    but I think it should also closes when we click on anywhere on page or 
                             after selecting theme colors it should automatically close
![image](https://github.com/Opentek-Org/opentek/assets/94105514/0e5bb7fc-0cff-4cd2-a133-7f5ccbbe318c)

**Comment by sunny0625** [comment]
The theme Feature is working fine.
