### ISSUE TITLE
FEATURE: Want to add Domain

### ISSUE THREAD

**Issue by Killer2OP** [Opentek-Org/opentek#345]
**Is your feature request related to a problem? Please describe.**
There are very limited domains in project section.

**Describe the solution you'd like**
So, I want to add more domains in it.
Example: IOS development , Artificial Intelligence , Web3 etc.

**Additional context**
Assign me this issue under GSSoC'23

**Comment by Killer2OP** [comment]
@AnirudhPanda Can you please assign me this issue.

**Comment by AnirudhPanda** [comment]
can you also add minimum 3 good projects in each domain? @Killer2OP

**Comment by Killer2OP** [comment]
> can you also add minimum 3 good projects in each domain? @Killer2OP

Yes i can do that.
