### ISSUE TITLE
Navbar overflow issue

### ISSUE THREAD

**Issue by MisterMickey** [Opentek-Org/opentek#348]
### Description

Navbar is being overflown 

### Screenshots

![Screenshot from 2023-06-25 02-03-21](https://github.com/Opentek-Org/opentek/assets/93720428/1671dd7f-2755-4f6a-86a0-bf8f177d4328)

### Additional information

Assign me under gssoc23

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by shubhamc1947** [comment]
hello sir i would like to work on this issue can you please assign this to me

**Comment by khadar1020** [comment]
hello sir [AnirudhPanda](https://github.com/AnirudhPanda) please assign me this issue
