### ISSUE TITLE
Enhance cards UI

### ISSUE THREAD

**Issue by MisterMickey** [Opentek-Org/opentek#349]
I want to enhance cards UI to make them look appealing and not totally out and weird as they are now

![Screenshot from 2023-06-25 02-08-19](https://github.com/Opentek-Org/opentek/assets/93720428/17f6d187-cb70-451a-b2dc-be7100e1a7c3)

**Comment by AnirudhPanda** [comment]
how would you like to enhance it? Have some designs? Please show @MisterMickey

**Comment by MisterMickey** [comment]
@AnirudhPanda 
1. I will center align all the text in the divs
2. I'll change the button design
3. (optional) change theme color for cards

**Comment by AnirudhPanda** [comment]
need some solid makeover to make this PR merged so all the best.

**Comment by MisterMickey** [comment]
@AnirudhPanda Would you mind if I change the theme color from pink to something else?
