### ISSUE TITLE
Add animation on scroll to the About Section on Home Page [GSSOC'23]

### ISSUE THREAD

**Issue by KaranKumar-97** [Opentek-Org/opentek#350]
**Is your feature request related to a problem? Please describe.**
- I want to improve the UI experience by adding animation on scroll to about section just like features section.

**Describe the solution you'd like**
add animation to each division of  texts while scrolling

**Additional context**
Can you please assign this issue to me under GSSOC'23

**Comment by AnirudhPanda** [comment]
is someone already doing this @sunny0625

**Comment by KaranKumar-97** [comment]
@AnirudhPanda can you please assign this issue to me ?
