### ISSUE TITLE
Critical SEO Tag Implementation Issues: missing tags which effect Search Engine Visibility and Performance GSSOC-23

### ISSUE THREAD

**Issue by Mrprayag077** [Opentek-Org/opentek#356]
### Description

SEO tags play a crucial role in optimizing web pages for search engines and improving their visibility in Google rankings. However, some pages in the application are currently lacking essential SEO tags, which can hinder their performance in search engine results pages (SERPs).

### TAGS:

> Lack of Metadata
> Missing Alt Attributes
> Lack of Structured Data (Schema.org markup)
> XML Sitemap many more

>     <meta name="robots" content="index, follow">
>     <meta name="google-site-verification" content="your_verification_code">
>     <meta name="csrf-token" content="your_csrf_token">
>     <meta name="msvalidate.01" content="your_verification_code">

### Screenshots

![pdcmdlmdl](https://github.com/Opentek-Org/opentek/assets/99162236/8918666d-7dfd-4ad0-bb99-3d85bdfe9826)

### Additional information
By adding important SEO tags such as meta title, meta description, and heading tags to our web pages, we can provide search engines with relevant information about the content and context of each page. These tags help search engines understand the purpose of our pages and match them with relevant user queries.

### Benefits:
 
- Improved Search Engine Visibility: Including SEO tags ensures that search engines can effectively crawl and index our web pages, leading to better visibility in search results.

- Higher Click-Through Rates (CTR): Well-optimized meta titles and descriptions can attract users' attention in search results, increasing the likelihood of them clicking on our pages.
 
- Enhanced User Experience: SEO tags, such as heading tags, help structure the content on our pages, making it more organized and user-friendly. This improves the overall user experience and encourages visitors to spend more time on our site.
 
- Targeted Keyword Optimization: By strategically incorporating relevant keywords in our SEO tags, we can align our content with user search intent and improve our rankings for specific queries.
 
- To enhance the SEO performance and indexing of our pages, it is essential to implement these missing SEO tags across the application. This will help us rank higher in Google search results, attract more organic traffic, and ultimately improve the overall success of our website.

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by AnirudhPanda** [comment]
please post the lighthouse score in the PR too

**Comment by Avinash905** [comment]
Please assign me if this issue is not been resolved so that I can work on this issue under **GSSOC'23**.

**Comment by Mrprayag077** [comment]
> 

i am already working on this issue
