### ISSUE TITLE
[BUG] Project cards not visible

### ISSUE THREAD

**Issue by Nachiket94** [Opentek-Org/opentek#362]
### Description

Project cards are not visible in the projects page.

### Screenshots

![Opentek Issue 2](https://github.com/Opentek-Org/opentek/assets/83511180/c477cabe-00c0-484d-ab59-d2f454819bb6)

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by AnirudhPanda** [comment]
can you fix this in 12 hours? @Nachiket94
