### ISSUE TITLE
Add projects DB in Projects Section

### ISSUE THREAD

**Issue by devWonderkind** [Opentek-Org/opentek#365]
**Is your feature request related to a problem? Please describe.**

Projects are not shown in the Projects section.
![opeentek](https://github.com/Opentek-Org/opentek/assets/110322061/b1125366-35dd-4b83-9573-c2698a516ec7)

**Describe the solution you'd like**

I wanna link projects DB  in the project section.
**Describe alternatives you've considered**

**Additional context**
Please assign this issue to me under GSSoC'23.

**Comment by AnirudhPanda** [comment]
did you find the problem?
