### ISSUE TITLE
Important checkboxes

### ISSUE THREAD

**Issue by parasss19** [Opentek-Org/opentek#366]
## Current
- There are no checkboxes in issue template
- When contributor (GSSOC'23) raise a new issue then many time they didn't mention GSSOC label
- It is also tough for project admin to label the issues

## Solution
- I will add the checkboxes so that its easy for both contributor and project admin to label the issues

### Screenshots

<img width="942" alt="Screenshot 2023-06-25 183208" src="https://github.com/Opentek-Org/opentek/assets/101205226/764b05ba-e042-4824-b5b6-b04f7b102791">

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by AnirudhPanda** [comment]
Hey the label thing is already automated through Github actions
