### ISSUE TITLE
FEATURE:- Display the projects and make a drag down for each option in the Projects page

### ISSUE THREAD

**Issue by PoulavBhowmick03** [Opentek-Org/opentek#369]
**Is your feature request related to a problem? Please describe.**
No projects are displayed in the Projects page

**Describe the solution you'd like**
Make a drop down and under each section, the projects will be displayed

![image](https://github.com/Opentek-Org/opentek/assets/133862694/cbc28326-3ad6-4da5-8d2d-31c87d094a99)

**Comment by PoulavBhowmick03** [comment]
@AnirudhPanda please look into this issue

**Comment by AnirudhPanda** [comment]
@sunny0625 is this an issue?

**Comment by PoulavBhowmick03** [comment]
@AnirudhPanda @sunny0625 You can check the website, the projects page, none are visible

**Comment by sunny0625** [comment]
Issue solved
