### ISSUE TITLE
FEATURE: Display tutorials of various lectures in the tutorials page

### ISSUE THREAD

**Issue by PoulavBhowmick03** [Opentek-Org/opentek#370]
**Is your feature request related to a problem? Please describe.**
In the tutorials page, currently there are no lectures displayed.

**Describe the solution you'd like**
I would like to add relevant lectures in the lectures page

![image](https://github.com/Opentek-Org/opentek/assets/133862694/09c6fe9d-9c46-403e-9498-d003b24218c9)
![image](https://github.com/Opentek-Org/opentek/assets/133862694/091d857c-3311-4072-8b3a-dfbbbfaed457)
and more

**Comment by PoulavBhowmick03** [comment]
@AnirudhPanda Please assign this to me

**Comment by AnirudhPanda** [comment]
what do you mean by lectures exactly?

**Comment by AnirudhPanda** [comment]
> > what do you mean by lectures exactly?
> 
> I have added screenshot of what I want to add. Currently, those tutorials are not displayed @AnirudhPanda

what you want to add?

**Comment by AnirudhPanda** [comment]
gotcha! please fix it asap
