### ISSUE TITLE
Scrolling bug 

### ISSUE THREAD

**Issue by akanksha984** [Opentek-Org/opentek#377]
### Description

![image](https://github.com/Opentek-Org/opentek/assets/97845909/e20d8043-cb90-480f-aee8-c1b1d5b644f1)

On scrolling both of them overlaps. I would like to fix it.
Please assign this issue to me under GSSOC'23 . I want to work on this.

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by sunny0625** [comment]
This issue has been solved!
