### ISSUE TITLE
[FEATURE]: Add a search bar in Projects section

### ISSUE THREAD

**Issue by Srishtikumari2002** [Opentek-Org/opentek#380]
Till now there is not any project listed in the projects section, but when there will be projects listed then a search bar would be helpful in direct search for any project or repository apart from the sorting projects with specific tags mentioned.
Here I am willing to add a search bar, before the tags in center:
![image](https://github.com/Opentek-Org/opentek/assets/77767357/23950ad1-4860-42ad-ac1d-0afb87330290)

**Comment by ARGHYADIPROY** [comment]
I am a GSSoC'23 contributor. I can add a search bar in projects section. I have all the skills required.
Please assign me this issue, I want to work on this issue under the GSSoC'23.
