### ISSUE TITLE
FEATURE : Adding more tutorials in Tutorials section

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [Opentek-Org/opentek#393]
Hello @AnirudhPanda ,
Adding more tutorials like a tutorial with **Code with Harry** and **Harkirat Singh** which is a well earner with open source how is the idea ?

## Screenshot - 
![image](https://github.com/Opentek-Org/opentek/assets/121503426/d7a2037c-080f-4531-9638-320ae62f8c41)

**Comment by AnirudhPanda** [comment]
which links?
