### ISSUE TITLE
Repeat of footer

### ISSUE THREAD

**Issue by AnirudhPanda** [Opentek-Org/opentek#398]
### Description

Refer to the ss

### Screenshots

![image](https://github.com/Opentek-Org/opentek/assets/66218496/07d22391-5df0-4bfb-8ee2-598b68e95d01)

### Do you want to work on this issue?

- [ ] I want to work on this issue.

**Comment by Ayush9951** [comment]
Hi @AnirudhPanda, I am contributor in Gssoc'23, please assign me this issue

**Comment by sunny0625** [comment]
> Hi @AnirudhPanda, please explain the expected behaviour, shall I remove bottom one and replace It with the top one ?

Could you remove the bottom one and change the copy write format to the current year?
