### ISSUE TITLE
Creating PWA for the website

### ISSUE THREAD

**Issue by AnirudhPanda** [Opentek-Org/opentek#40]
PWA is intended to work on any platform that uses a standards-compliant browser, including both desktop and mobile devices.

Refer this video - https://youtu.be/E8BeSSdIUW4

**Comment by AnirudhPanda** [comment]
PWA is intended to work on any platform that uses a standards-compliant browser, including both desktop and mobile devices.

Refer this video - https://youtu.be/E8BeSSdIUW4

**Comment by neeraj15022001** [comment]
I would link to pick this one

**Comment by AnirudhPanda** [comment]
> I would link to pick this one

Assigned!
Keep me updating!

Also, you can join our [Discord ](https://discord.gg/gpWExMrK)for any queries!
