### ISSUE TITLE
footer is repeated 

### ISSUE THREAD

**Issue by khadar1020** [Opentek-Org/opentek#401]
### Description

in the index.html page, the footer is repeated 2 times

### Screenshots

![Screenshot (390)](https://github.com/Opentek-Org/opentek/assets/124120102/4e688b11-cefd-4225-8766-9a640b31afc7)

### Additional information

we can change the display property.I have already changed the code if you assign me then I will send the pr.

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by sunny0625** [comment]
This issue has already been taken.
reference: #398
