### ISSUE TITLE
Dockerize project

### ISSUE THREAD

**Issue by shraddha761** [Opentek-Org/opentek#407]
**Is your feature request related to a problem? Please describe.**
Create a docker file for project which help to you to package your application and its dependencies into a container, making it highly portable. The Docker image can be run on any system that supports Docker, ensuring consistent behavior across different environments. It allow you define the exact steps needed to build your application environment. By versioning your Dockerfile, you can reproduce the exact same environment at any point in the future. This helps avoid "it works on my machine" issues and facilitates collaboration among team members.

assign this issue to me under GSSOC'23

**Comment by AnirudhPanda** [comment]
assigning this to you. Make sure to add proper instructions for newbie in the readme file for this

**Comment by shraddha761** [comment]
@AnirudhPanda please review my pr
