### ISSUE TITLE
aligning the contact us section in the center of the page

### ISSUE THREAD

**Issue by shruuti321** [Opentek-Org/opentek#412]
I would like to align the contact us section to the center of the page.
![image](https://github.com/Opentek-Org/opentek/assets/114770273/d3608c67-ca67-405b-a262-4509a4fe9099)

**Comment by manoranjanonline** [comment]
please assign me this issue i will solve under GSSOC'23

**Comment by AnirudhPanda** [comment]
Not needed as of now
