### ISSUE TITLE
FEATURE Login page need UI improvement

### ISSUE THREAD

**Issue by HimanshuNarware** [Opentek-Org/opentek#427]
**Is your feature request related to a problem? Please describe.**
The login page UI is not looking good
**Describe the solution you'd like**
Need UI improvement according to the theme of the website
**Describe alternatives you've considered**
this will improve the UI
**Additional context**
Screenshot
![21](https://github.com/Opentek-Org/opentek/assets/83147410/2f91c68f-eb78-4f60-a5e6-2e922253f95d)

**Comment by karantec** [comment]
I would like to work on the project. Can you assign the project to me under 2023

**Comment by sunny0625** [comment]
is this gtg @AnirudhPanda ?

**Comment by AnirudhPanda** [comment]
The UI is by AUTH0 itsef. No changes reqd
