### ISSUE TITLE
Footer section in all pages

### ISSUE THREAD

**Issue by Sushilverma002** [Opentek-Org/opentek#429]
**Is your feature request related to a problem? Please describe.**
The home page footer is ok but we have to make same for other pages tooo like on project section and other sections.

**Describe the solution you'd like**
Home Page:-
![Screenshot_20230706-223640](https://github.com/Opentek-Org/opentek/assets/114687502/f39b9408-6261-455f-860b-a993e4c045db)
Other page like project etc
![Screenshot_20230706-223703](https://github.com/Opentek-Org/opentek/assets/114687502/ce742d09-88a6-4741-9bdc-2609d96ee747)

**Describe alternatives you've considered**

**Additional context**

**Comment by karantec** [comment]
please assign me this issue i will solve under GSSOC'23
