### ISSUE TITLE
FEATURE : Adding Testimonial Page and Testimonial Collection Form

### ISSUE THREAD

**Issue by Nishitbaria** [Opentek-Org/opentek#434]
**Issue Description:**
As a contributor to the OpenTek website, I propose adding a Testimonial page to showcase feedback and testimonials from users. This will provide social proof and enhance the credibility of our services. Additionally, I suggest creating a Testimonial Collection Form to streamline the process of collecting testimonials from users.

**Proposed Changes:**
1. Testimonial Page:
   - Create a new page on the OpenTek website dedicated to testimonials.
   - Design the page layout to display testimonials in an organized and visually appealing manner.
   - Implement a responsive design to ensure optimal viewing on different devices.
   - Add appropriate sections to display testimonials, including the testimonial text, name of the user, and optionally, their profile picture.
   - Consider adding filters or categories to group testimonials based on relevant criteria, such as service type or industry.

2. Testimonial Collection Form:
   - Develop a user-friendly testimonial collection form where users can submit their testimonials.
   - Include fields for the user's name, email address, organization (optional), testimonial text, and the option to upload a profile picture (optional).
   - Implement form validation to ensure the required fields are filled correctly.
   - Consider incorporating a captcha or spam protection mechanism to prevent misuse of the form.
   - Connect the form to a backend service or email notification system to receive and store submitted testimonials securely.

**Expected Benefits:**
- Enhance the credibility of the OpenTek website by showcasing positive feedback from users.
- Provide a platform for users to share their experiences and insights, contributing to a sense of community and trust.
- Improve user engagement and encourage new users to explore OpenTek's services based on the positive testimonials.
- Streamline the testimonial collection process, making it easier for users to submit their feedback.

**Additional Considerations:**
- Ensure the design and implementation align with OpenTek's existing branding and website style.
- Test the testimonial collection form thoroughly to ensure proper functionality and data validation.
- Implement appropriate data privacy measures, such as obtaining user consent and complying with relevant regulations (e.g., GDPR).

This issue will significantly enhance the OpenTek website by adding a dedicated Testimonial page and implementing a Testimonial Collection Form. It will strengthen our online presence and provide valuable insights to potential users.

**Comment by Nishitbaria** [comment]
@AnirudhPanda ,please assign me this issue

**Comment by Nishitbaria** [comment]
@AnirudhPanda ,I have to make new page or Add it in Home page

**Comment by Nishitbaria** [comment]
@AnirudhPanda ,Where should i keep the testimonial form button ?

**Comment by Nishitbaria** [comment]
@AnirudhPanda ,please review my pull request

**Comment by AnirudhPanda** [comment]
DONE AND DUSTED

THANKS @Nishitbaria
