### ISSUE TITLE
Add more video data 

### ISSUE THREAD

**Issue by AlfiyaSiddique** [Opentek-Org/opentek#437]
I would like to add more videos in the data section of the video. I would add videos related to how to find issues on GitHub and how to find projects related to your skill on GitHub and much more.

I am a gssoc23 contributor please assign me this issue under gssoc23 label

**Comment by AnirudhPanda** [comment]
paste the video links here first

**Comment by AlfiyaSiddique** [comment]
Hello @AnirudhPanda , following are the videos I want to add

Video Links
1. How to find Github Repos to contribute to... (Relevant to you!) **By Ben Kadel**
https://youtu.be/W7AewHnxMig

2. How to Find Good First Issues in Open Source? **By Kunal kushwaha**
https://youtu.be/ZIkkPzTuOXw

3. 25+ Paid Open Source Programs and Internships **By Kunal Kushwaha**
https://youtu.be/x4hsV_q_YQc

4. How to Open Source Like a Pro **By Ben Awad**
https://youtu.be/MT6M_sqAuZo

5. Git for Professionals Tutorial - Tools & Concepts for Mastering Version Control with Git **By FreeCodeCamp**
https://youtu.be/Uszj_k0DGsg
