### ISSUE TITLE
Add Road Map Section

### ISSUE THREAD

**Issue by AlfiyaSiddique** [Opentek-Org/opentek#439]
**Is your feature request related to a problem? Please describe.**
I would like to propose the addition of a Road Map Page. 
In my opinion, the Pre-requisite of getting into open source is to learn at least the basic of one skill's tech or tech stack properly and then git and GitHub.
As our site is all about open source, the addition of road map's like frontend-development, backend-development, mobile-app-development, machine learning, etc. will be worth implementing for users and help them to reach opensource. 
Adding road maps will help the user to know at which point they should get into open source in a journey of learning a particular skill.

**Describe the solution you'd like**
I will add a road map page for listing different skills in the form of cards whose roadmap will be present on our site. 
The link to this page will be visible on the navbar.
On clicking on a particular skill roadmap card another page will open which will contain the actual road map information.
I will make the designs and layout of the roadmap page similar to the rest of the website.
The layout and design of the roadmap Info page will be in the form of a timeline.

If you agree on this feature, To start with I can add the roadmap of full stack web development with **mern** tech stack and fronted web development.

Later contributors can add more roadmaps as well. I'll try to make the code reusable.

I will also share the output video before making a PR.

If you find this worth implementing then please assign me this issue under gssoc23.

**Comment by AnirudhPanda** [comment]
are you working on it @AlfiyaSiddique

**Comment by AlfiyaSiddique** [comment]
> are you working on it @AlfiyaSiddique

@AnirudhPanda Yes I'm working on it, the development is a little slow cause I'm busy with some other work, but  I will submit a PR for this issue by the end of tomorrow

**Comment by AlfiyaSiddique** [comment]
Hello @AnirudhPanda.

I have completed it till here. 👇🏻👇🏻
Some minor changes are still remaining, But I need your feedback on this. 
Let me know if you have any suggestions or want me to change anything. 



https://github.com/Opentek-Org/opentek/assets/86224794/65979e61-2c24-4886-bbeb-d7f47f7c4b16

**Comment by AlfiyaSiddique** [comment]
@AnirudhPanda  please provide your feedback for further progress.

**Comment by AnirudhPanda** [comment]
yea looks good. Adding more would be good
