### ISSUE TITLE
want to create a contact section in right empty space

### ISSUE THREAD

**Issue by Sushilverma002** [Opentek-Org/opentek#442]
**Is your feature request related to a problem? Please describe.**
the empty space make website odd.
**Describe the solution you'd like**
 we can make a contact section consisting :
name 
email
subject 
message 
look like that:-
![image](https://github.com/Opentek-Org/opentek/assets/114687502/9aca5e46-c39b-45f3-9079-46acc081dec8)

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/Opentek-Org/opentek/assets/114687502/1c798dee-ea79-4694-96e4-3d1d64716b33)

**Comment by AnirudhPanda** [comment]
where will the responses go?

**Comment by AnirudhPanda** [comment]
not necessary at the moment
