### ISSUE TITLE
Add Cross button on Login page

### ISSUE THREAD

**Issue by Priyaaa1** [Opentek-Org/opentek#448]
### Description

When I click on Login button, there is no Cross button to close the Login page or redirect the user back to Home page.
I would like to resolve this issue. Please assign me this issue under GSSoC'23 label.

Thankyou!!

### Screenshots

![Screenshot (152)](https://github.com/Opentek-Org/opentek/assets/105431748/d14523c9-c46a-4a61-830b-33e1fdcc0166)

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by AnirudhPanda** [comment]
Currently, we do not need that. Thank you so much and keep looking for bugs
