### ISSUE TITLE
FIX THE README OF THIS PROJECT

### ISSUE THREAD

**Issue by AnirudhPanda** [Opentek-Org/opentek#452]
### Description

there are few symbol errors here and there which broke the readme.

### Do you want to work on this issue?

- [ ] I want to work on this issue.

**Comment by Ayush9951** [comment]
Hi @AnirudhPanda, I am a contributor in GSSOC'23,
you can assign me this task

**Comment by AnirudhPanda** [comment]
Done @Ayush9951 
need this asap

**Comment by Ayush9951** [comment]
> 

Hi, please explain what exactly is the issue in readme?

**Comment by AnirudhPanda** [comment]
see yourself you will understand if you know MARKDOWN

**Comment by AnirudhPanda** [comment]
Hey @Ayush9951 
I will be revamping the whole readme today!!
So you can solve the other issue assigned to you and leave this on me

**Comment by Ayush9951** [comment]
ok Anirudh
