### ISSUE TITLE
Add Link in Discord

### ISSUE THREAD

**Issue by Ayush9951** [Opentek-Org/opentek#453]
Hi @AnirudhPanda,
In the Discord banner there is no link available
I want to work on this issue
please assign me this task under label gssoc'23

![Screenshot 2023-07-12 183250](https://github.com/Opentek-Org/opentek/assets/60573378/a6c608fc-10ec-4fe0-bd92-c2ad041f9b8d)

**Comment by AnirudhPanda** [comment]
find a way so that the link won't expire
