### ISSUE TITLE
FEATURE Add Instagram icon in the socials

### ISSUE THREAD

**Issue by blindaks** [Opentek-Org/opentek#455]
**Is your feature request related to a problem? Please describe.**
I want to add a link to Instagram with the other socials.

**Describe the solution you'd like**
A clear and concise description of what you want to happen.![Screenshot (52)](https://github.com/Opentek-Org/opentek/assets/128223364/b9b2cec8-188b-4189-b244-9c9f52333691)
**Describe alternatives you've considered**

**Additional context**

**Comment by blindaks** [comment]
@AnirudhPanda Please assign this issue to me under GSSOC'23.

**Comment by AnirudhPanda** [comment]
we do not have instagram
