### ISSUE TITLE
the footer look different 

### ISSUE THREAD

**Issue by Sushilverma002** [Opentek-Org/opentek#464]
### Description
page job portal
currently-
![image](https://github.com/Opentek-Org/opentek/assets/114687502/08988a60-0a18-4d66-b7fb-b1eea03e0f3a)
but actually have to like this:
![image](https://github.com/Opentek-Org/opentek/assets/114687502/e69f4280-3265-4785-bd9b-4a97605c5f15)

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by Sushilverma002** [comment]
@AnirudhPanda

**Comment by AnirudhPanda** [comment]
okay fix this in all the pages
