### ISSUE TITLE
About the chatbot

### ISSUE THREAD

**Issue by SaiSathvik6** [Opentek-Org/opentek#473]
### Description

there is no option to close the chatbot and it's overriding the page. Not aligned properly

### Screenshots

<img width="602" alt="image" src="https://github.com/Opentek-Org/opentek/assets/97099124/5f9cd5cf-38a3-4aa8-8413-a14a7e83a3b3">

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by AnirudhPanda** [comment]
@Nishitbaria please see into this issue
