### ISSUE TITLE
Missing "is" in About Us page

### ISSUE THREAD

**Issue by blindaks** [Opentek-Org/opentek#478]
### Description

On the About Us page, it is written "If it about Open Source, it is on Opentek".

### Screenshots

![Screenshot (60)](https://github.com/Opentek-Org/opentek/assets/128223364/5b0a1718-7a4f-4e73-be9d-910747b0bf3d)

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by blindaks** [comment]
@AnirudhPanda Please assign this issue to me.

**Comment by AnirudhPanda** [comment]
Do a thing, find all such spelling errors in the website and resolve them
