### ISSUE TITLE
About the Chatbot 

### ISSUE THREAD

**Issue by SaiSathvik6** [Opentek-Org/opentek#479]
### Description

once we chat with the chatbot, it is not close on refreshing the page or it's not closing on reopening the page on pc.

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by AnirudhPanda** [comment]
@Nishitbaria

**Comment by Nishitbaria** [comment]
@AnirudhPanda ,I will fix the issue and create pull requesta asap,assign me this issue

**Comment by AnirudhPanda** [comment]
Yes please fix all the sizing issues of chatbot

**Comment by Nishitbaria** [comment]
@AnirudhPanda ,please review and merge my pull request

**Comment by Nishitbaria** [comment]
@AnirudhPanda ,I have created issue for adding api call to delete testimonial ,please assign it to me
