### ISSUE TITLE
Issue in Quick links

### ISSUE THREAD

**Issue by Priyaaa1** [Opentek-Org/opentek#485]
### Description

In Quick links, "About us" and "Projects" pages aren't opening. I want to work on this issue and fix it.
Thankyou!!

### Screenshots

![Screenshot (158)](https://github.com/Opentek-Org/opentek/assets/105431748/8777bb6e-40b9-46e5-8ad0-ea70c8ade566)
![Screenshot (160)](https://github.com/Opentek-Org/opentek/assets/105431748/83cdfb7d-9bd0-4eb6-9342-7d2d7f4d30cf)

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by AnirudhPanda** [comment]
fix all the broken links! THanks
