### ISSUE TITLE
[Feat]: Add new page for blogs 

### ISSUE THREAD

**Issue by Swapnil-2503** [Opentek-Org/opentek#495]
### Is your feature request related to a problem? Please describe.

adding new page in https://opentek.in/pages/tutorial.html blogs there are only videos  

### Describe the solution you'd like.

I will create new page for blogs where we can add different blogs as tutorial

### Show us the magic with screenshots

![Screenshot 2023-07-17 112741](https://github.com/Opentek-Org/opentek/assets/89910173/74162476-82dc-4527-9965-6e78f391d09f)

**Comment by Swapnil-2503** [comment]
@AnirudhPanda please assign this to me

**Comment by AnirudhPanda** [comment]
We already have it
