### ISSUE TITLE
Adding tutorials in navbar of home 

### ISSUE THREAD

**Issue by Swapnil-2503** [Opentek-Org/opentek#502]
### Description

currently we can see tutorials in projects section but users cannot go to see tutorials directly from home navbar so we need add it.
![Screenshot 2023-07-17 112741](https://github.com/Opentek-Org/opentek/assets/89910173/4eebce70-7f4b-445c-8bf4-60b79ff41e4c)

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by Swapnil-2503** [comment]
@AnirudhPanda

**Comment by AnirudhPanda** [comment]
Not required at the moment
