### ISSUE TITLE
fix: tutorial videos

### ISSUE THREAD

**Issue by AnirudhPanda** [Opentek-Org/opentek#540]
### Description

Refer to the screenshot.

there is a icon on every video

### Screenshots

![image](https://github.com/Opentek-Org/opentek/assets/66218496/3e19df2a-62cf-49a0-8d23-8e6449ef670c)

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the [existing issues](https://github.com/Opentek-Org/opentek/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/Opentek-Org/opentek/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue. (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by parasss19** [comment]
Hey i want to work in this issue
