### ISSUE TITLE
Add Animations (AOS) on Homepage

### ISSUE THREAD

**Issue by AnirudhPanda** [Opentek-Org/opentek#56]
Refer: https://michalsnik.github.io/aos/

Animations on scroll would look great on the homepage according to me!
If you have any other suggestions on **how to make the homepage look more eye-catchy** comment on  this *ISSUE* or Open a new issue [here](https://github.com/Opentek-Org/opentek/issues/new/choose)

Join our [Discord](https://discord.gg/UKd4W25n) if you want to discuss anything!

**Comment by neeraj15022001** [comment]
Do one thing let me combine all homepage related issues here i will solve in one go

**Comment by neeraj15022001** [comment]
#21 #57 #23

**Comment by AnirudhPanda** [comment]
> #21 #57 #23

Amazing!!!

Thank you for taking the issues @neeraj15022001 ⚡

**Comment by neeraj15022001** [comment]
put me as asignee i will start these after previous issue

**Comment by neeraj15022001** [comment]
https://user-images.githubusercontent.com/55191873/133639893-7342a846-3db5-4b07-805c-f4f66dfb2a1f.mp4

Progress till now on these three issue :
- Working on navbar there is some issue coming while changing icon
- Illustration changed - will change if i came across some better
- Fixed order of second illustration on smaller screen size ( now there is no need to hide it )
- Made spacing in footer and added new underline effect on links

**Comment by neeraj15022001** [comment]
@AnirudhPanda check this video

**Comment by AnirudhPanda** [comment]
> * in footer and added new underline effect on links

The progress Looks Great @neeraj15022001 

Should we add AOS on the cards as well? Will it look good?

**Comment by neeraj15022001** [comment]
> > * in footer and added new underline effect on links
> 
> The progress Looks Great @neeraj15022001 
> 
> Should we add AOS on the cards as well? Will it look good?
> 

Will think on that

**Comment by AnirudhPanda** [comment]
> > > * in footer and added new underline effect on links
> > 
> > 
> > The progress Looks Great @neeraj15022001
> > Should we add AOS on the cards as well? Will it look good?
> 
> Will think on that

Cool!
Let me share this PR on Discord

**Comment by neeraj15022001** [comment]
https://user-images.githubusercontent.com/55191873/133704347-6650a303-cd47-4ec7-be88-04fe702befcb.mov

Added Close Button to Navbar in reference to issue number #23

**Comment by neeraj15022001** [comment]
in reference to issue number #23 #21 changes are done
Navbar : Added close button 
Footer : Fixed responsiveness and added underline effect with faster transitions

#57  Issue is almost done just searching new illustrations

**Comment by AnirudhPanda** [comment]
> in reference to issue number #23 #21 changes are done
> Navbar : Added close button
> Footer : Fixed responsiveness and added underline effect with faster transitions
> 
> #57 Issue is almost done just searching new illustrations

Great work!!

**Comment by neeraj15022001** [comment]
About AOS i believe AOS involves lots of javascript processing as there is continuous event listener listening to scrolls so it will reduce website performance and on top of that it sometimes breaks existing code, so i believe we should not add that

**Comment by neeraj15022001** [comment]
![Screenshot 2021-09-18 at 6 40 01 PM](https://user-images.githubusercontent.com/55191873/133890013-06887399-9727-46e5-820b-89effe5fc511.png)
Illustration Changed on About Page
![Screenshot 2021-09-18 at 6 40 58 PM](https://user-images.githubusercontent.com/55191873/133890044-78999bc1-045c-4aa5-be25-2962d1483ac9.png)
Illustration changed on home screen for about us section

**Comment by AnirudhPanda** [comment]
> ![Screenshot 2021-09-18 at 6 40 01 PM](https://user-images.githubusercontent.com/55191873/133890013-06887399-9727-46e5-820b-89effe5fc511.png)
> Illustration Changed on About Page
> ![Screenshot 2021-09-18 at 6 40 58 PM](https://user-images.githubusercontent.com/55191873/133890044-78999bc1-045c-4aa5-be25-2962d1483ac9.png)
> Illustration changed on home screen for about us section

the bottom one sizing has to be done!

**Comment by neeraj15022001** [comment]
Then it will look way to small that's why i even scaled it up, instead we can center the content of right part. What's your thought on that?

**Comment by AnirudhPanda** [comment]
> Then it will look way to small that's why i even scaled it up, instead we can center the content of right part. What's your thought on that?

Isn't the animation way too large? Yeah we can try that ig

**Comment by neeraj15022001** [comment]
If i will reduce the size it will not have that much impact i mean it will look that tiny that purpose of adding image will get destroyed. Rest you can think and tell

**Comment by neeraj15022001** [comment]
i will make changes accordingly

**Comment by AnirudhPanda** [comment]
Ok, I understand!

We can center that then and if we get better ideas we will modify that on a later stage

**Comment by AnirudhPanda** [comment]
Planning this!!

https://user-images.githubusercontent.com/66218496/133971277-cdd4e65c-a31e-4965-a466-2c67307658b5.mp4

**Comment by neeraj15022001** [comment]
Great, this can replace current illustrations. What is source of these illustrations

**Comment by AnirudhPanda** [comment]
> Great, this can replace current illustrations. What is source of these illustrations

Canva

**Comment by neeraj15022001** [comment]
hey @AnirudhPanda should i close this PR now and create seperate PR's ?

**Comment by neeraj15022001** [comment]
@AnirudhPanda shall i add AOS ?

**Comment by neeraj15022001** [comment]
@AnirudhPanda can you tell me status for this issue if we need to add AOS or not ?

**Comment by nawed2611** [comment]
Hi!, I wanted to work on this issue.

**Comment by neeraj15022001** [comment]
@AnirudhPanda please close this i case this is resolved
