### ISSUE TITLE
Find good animated pictures/gif/svg for homepage

### ISSUE THREAD

**Issue by AnirudhPanda** [Opentek-Org/opentek#57]
For the time being, I have added SVG from undraw but that doesn't really look great on the homepage!
The task is to find good and free resources that we can use to make the homepage look more attractive.
Make sure the animations don't belong to any religion, color, caste, etc

**Comment by neeraj15022001** [comment]
I have some good options, we can resolve this during hacktoberfest

**Comment by AnirudhPanda** [comment]
> I have some good options, we can resolve this during hacktoberfest

Sure!!
We can talk here about it

**Comment by neeraj15022001** [comment]
So, assign this we will pick this later, right now UI needs to be revamped first
