### ISSUE TITLE
🚀 Adding Backend Roadmap 🛤️📈

### ISSUE THREAD

**Issue by Nishitbaria** [Opentek-Org/opentek#573]
### About

Create a roadmap outlining the backend development plan, including features, improvements, and milestones for the project. This roadmap will provide a clear direction for the backend development and help prioritize tasks effectively. 🌟💻

### Add a Screenshot of your project to the list

![backend_001](https://github.com/Opentek-Org/opentek/assets/85815172/a36641c6-f75b-4bd5-b923-af2b44f2f27a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

### Select the Project Type

None

**Comment by Nishitbaria** [comment]
@AnirudhPanda Please Review my pr

**Comment by TANISHQ-GUPTA12** [comment]
HEY @Nishitbaria @AnirudhPanda 

CAN YOU ASSIGN THIS TASK TO ME 

I M WILLING TO WORK ON THIS ISSUE

**Comment by Nishitbaria** [comment]
@TANISHQ-GUPTA12 I am already working and will make PR
