### ISSUE TITLE
 🚀 Creating Data Science Month-wise Roadmap 🛤️📅

### ISSUE THREAD

**Issue by Nishitbaria** [Opentek-Org/opentek#574]
### About

 Develop a month-wise roadmap for Data Science, outlining the tasks, projects, and learning objectives for each month. This roadmap will serve as a guide to structure and progress in Data Science, allowing for efficient planning and skill development. 🌟📊

### Add a Screenshot of your project to the list

![Fp854JaakAA3NEA](https://github.com/Opentek-Org/opentek/assets/85815172/3c94e848-74ca-4164-a1c0-c1b284dcb6fe)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I want to work on this issue

### Select the Project Type

None

**Comment by Nishitbaria** [comment]
@AnirudhPanda Please Review my pr

**Comment by TANISHQ-GUPTA12** [comment]
@Nishitbaria CAN YOU ASSIGN THIS TASK TO ME?

I  would love to draw a roadmap for Data Science, outlining 
-tasks,
-projects
-learning objectives for each month.

**Comment by Nishitbaria** [comment]
@TANISHQ-GUPTA12 You can make issue and get this assign for you on your own because I am working on this issue
