### ISSUE TITLE
[ FEATURE ] Add more OPEN SOURCE programs and events

### ISSUE THREAD

**Issue by AnirudhPanda** [Opentek-Org/opentek#69]
Follow https://github.com/Opentek-Org/opentek/blob/main/CONTRIBUTING.md to know where to add!

**Comment by lynx1902** [comment]
Hi Anirudh! I would like to work on this issue. Can you please assign it to me.

**Comment by AnirudhPanda** [comment]
> Hi Anirudh! I would like to work on this issue. Can you please assign it to me.

What are you planning to add?

**Comment by prakhar728** [comment]
I would like to work on the issue. Can you assign it to me? I already have the changes ready on local machine.

**Comment by AnirudhPanda** [comment]
> I would like to work on the issue. Can you assign it to me? I already have the changes ready on local machine.

What are you planning to add?

**Comment by prakhar728** [comment]
MLH fellowship- Open Source tracks that run throughout the year.

**Comment by AnirudhPanda** [comment]
> MLH fellowship- Open Source tracks that run throughout the year.

Okay

**Comment by lynx1902** [comment]
I wanted to add GirlScript Summer of  Code, Outreachy and some other programs.

**Comment by prakhar728** [comment]
Should I create a PR?

**Comment by manavdesai27** [comment]
@AnirudhPanda can I work on this issue?

**Comment by kushagra487** [comment]
I would like to work on this issue. Could you assign it to me? SWOC'21

**Comment by ayush-sleeping** [comment]
Hey @AnirudhPanda ,  ` "  Assign " `   me this issue under " SWoC'21 " .

I want to add these open source programs :-

September month - Semester Long Projects (SLoP by DA-IICT)
November month - Kharagpur Open Source Society  (KWoC)
November month - DevScript Winter of code.
