### ISSUE TITLE
Home Button does not work

### ISSUE THREAD

**Issue by kashish-d** [Opentek-Org/opentek#75]
### Description

The home button does not work as expected.  Suppose i am on the Projects page, it does not let me go to the home page again. It works, but this behaviour is already added to Go to top button that appears right bottom

### Do you want to work on this issue?

- [X] I want to work on this issue.

**Comment by nileshkr17** [comment]
> ### Description
> The home button does not work as expected. Suppose i am on the Projects page, it does not let me go to the home page again. It works, but this behaviour is already added to Go to top button that appears right bottom
> 
> ### Screenshots
> _No response_
> 
> ### Additional information
> _No response_
> 
> ### Do you want to work on this issue?
> * [x]  I want to work on this issue.

Some more bugs are there ,like that hamburger to cross in MOBILE navbar only working in home page.

**Comment by nileshkr17** [comment]
I would like to work on it.
