### ISSUE TITLE
Correct the typo

### ISSUE THREAD

**Issue by Ayushi7456** [Opentek-Org/opentek#77]
![issue](https://user-images.githubusercontent.com/78416191/135566465-6e017bb9-b9cb-44db-b47e-7910f70b9c15.JPG)
In the first point, it should be 'If you are' instead of 'If are'.

**Comment by Ayushi7456** [comment]
I would like to fix this issue. Please assign me under Hactoberfest.

**Comment by AnirudhPanda** [comment]
Hey @Ayushi7456 I believe the whole grammar issue is being resolved under #81 this  PR
Would you like to take another issue?
