### ISSUE TITLE
BUG: Join Us link is broken on the Website

### ISSUE THREAD

**Issue by AnirudhPanda** [Opentek-Org/opentek#96]
### Description

Redirect it to: https://github.com/Opentek-Org/support

### Do you want to work on this issue?

- [ ] I want to work on this issue.

**Comment by Adem68** [comment]
Can you assign to me?

**Comment by AnirudhPanda** [comment]
This issue is already assigned! Please take some other issues we have!

**Comment by adithyanandakumar** [comment]
@AnirudhPanda Had already created a pull request! In case the assigned person did not solve the issue, please merge it
